/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

/**
 *
 * @author ernes
 */
public class clientes extends javax.swing.JPanel {

    /**
     * Creates new form clientes
     */
    public clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id_cli = new javax.swing.JTextField();
        txt_nom_cli = new javax.swing.JTextField();
        txt_tel_cli = new javax.swing.JTextField();
        txt_dir_cli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_mail_cli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dni_cli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_iva = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(47, 34, 23));
        setPreferredSize(new java.awt.Dimension(1050, 575));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_id_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_id_cli.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_cli.setText("muestr sifguiente id");
        txt_id_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_cliActionPerformed(evt);
            }
        });
        add(txt_id_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 80, -1));

        txt_nom_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_nom_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_nom_cli.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_nom_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 240, -1));

        txt_tel_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_tel_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 140, -1));

        txt_dir_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_dir_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_dir_cli.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_dir_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 240, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, 20));

        txt_mail_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_mail_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_mail_cli.setForeground(new java.awt.Color(255, 255, 255));
        txt_mail_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mail_cliActionPerformed(evt);
            }
        });
        add(txt_mail_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 240, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(228, 575));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 740));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DNI");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        txt_dni_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_dni_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_dni_cli.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_dni_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 140, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria IVA");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        cb_iva.setForeground(new java.awt.Color(255, 255, 255));
        cb_iva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consumidor final", "Exento", "Exterior", "IVA no alcanzado", "Monotributista", "Responsable inscripto", " ", " " }));
        add(cb_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_cliActionPerformed

    private void txt_mail_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mail_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mail_cliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_dir_cli;
    private javax.swing.JTextField txt_dni_cli;
    private javax.swing.JTextField txt_id_cli;
    private javax.swing.JTextField txt_mail_cli;
    private javax.swing.JTextField txt_nom_cli;
    private javax.swing.JTextField txt_tel_cli;
    // End of variables declaration//GEN-END:variables
}
