/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

import db.MetodosSQL;
import java.awt.Color;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelos.Cliente;
import utils.Helper;

/**
 *
 * @author ernes
 */
public class ClientesFrame extends javax.swing.JPanel {

    /**
     * Creates new form clientes
     */
    public ClientesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreCli = new javax.swing.JTextField();
        txtTelCli = new javax.swing.JTextField();
        lblNombreCli = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtApellidoCli = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboCatIva = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JPanel();
        btn_regis2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnGuardarCliente = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_regis4 = new javax.swing.JPanel();
        txtDirCli = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtDniCli = new javax.swing.JTextField();

        setBackground(new java.awt.Color(47, 34, 23));
        setPreferredSize(new java.awt.Dimension(1050, 575));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreCli.setBackground(new java.awt.Color(47, 34, 23));
        txtNombreCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreCli.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreCliKeyReleased(evt);
            }
        });
        add(txtNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 240, -1));

        txtTelCli.setBackground(new java.awt.Color(47, 34, 23));
        txtTelCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTelCli.setForeground(new java.awt.Color(255, 255, 255));
        txtTelCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelCliKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelCliKeyReleased(evt);
            }
        });
        add(txtTelCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 240, -1));

        lblNombreCli.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreCli.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCli.setText("Nombre");
        add(lblNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 240, -1));

        lblDireccion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Direccion");
        add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        txtApellidoCli.setBackground(new java.awt.Color(47, 34, 23));
        txtApellidoCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtApellidoCli.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCliActionPerformed(evt);
            }
        });
        txtApellidoCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoCliKeyReleased(evt);
            }
        });
        add(txtApellidoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 240, -1));

        lblApellido.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellidos");
        add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 90, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(228, 575));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 740));

        lblDNI.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI.setText("DNI");
        add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 240, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria IVA");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        cboCatIva.setForeground(new java.awt.Color(255, 255, 255));
        cboCatIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consumidor final", "Exento", "Exterior", "Monotributista", "Responsable inscripto" }));
        add(cboCatIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 240, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 0));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });
        btnCancelar.setLayout(new java.awt.GridBagLayout());

        btn_regis2.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis2MouseClicked(evt);
            }
        });
        btn_regis2.setLayout(new java.awt.GridBagLayout());
        btnCancelar.add(btn_regis2, new java.awt.GridBagConstraints());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cancelar");
        btnCancelar.add(jLabel11, new java.awt.GridBagConstraints());

        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 110, 40));

        btnGuardarCliente.setBackground(new java.awt.Color(255, 102, 0));
        btnGuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarClienteMouseClicked(evt);
            }
        });
        btnGuardarCliente.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Guardar");
        btnGuardarCliente.add(jLabel12, new java.awt.GridBagConstraints());

        btn_regis4.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis4MouseClicked(evt);
            }
        });
        btn_regis4.setLayout(new java.awt.GridBagLayout());
        btnGuardarCliente.add(btn_regis4, new java.awt.GridBagConstraints());

        add(btnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 110, 40));

        txtDirCli.setBackground(new java.awt.Color(47, 34, 23));
        txtDirCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDirCli.setForeground(new java.awt.Color(255, 255, 255));
        txtDirCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDirCliKeyReleased(evt);
            }
        });
        add(txtDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 240, -1));

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Teléfono");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        txtDniCli.setBackground(new java.awt.Color(47, 34, 23));
        txtDniCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDniCli.setForeground(new java.awt.Color(255, 255, 255));
        txtDniCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniCliActionPerformed(evt);
            }
        });
        txtDniCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDniCliKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniCliKeyReleased(evt);
            }
        });
        add(txtDniCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCliActionPerformed

    private void btn_regis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis2MouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        Home.mostrarPanel(Home.VENTAS_FRAME);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btn_regis4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis4MouseClicked

    private void btnGuardarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarClienteMouseClicked
        if (Helper.esCampoVacio(txtDniCli)) {
            Helper.mostrarError(txtDniCli, lblDNI, "Debe ingresar DNI", Color.red);
            return;
        }
        if (Helper.esCampoVacio(txtNombreCli)) {
            Helper.mostrarError(txtNombreCli, lblNombreCli, "Debe ingresar Nombre", Color.red);
            return;
        }
        if (Helper.esCampoVacio(txtApellidoCli)) {
            Helper.mostrarError(txtApellidoCli, lblApellido, "Debe ingresar Apellido", Color.red);
            return;
        }

        // obtener clientes y filtrar si ya hay un dni registrado
        List<Cliente> listaDni = MetodosSQL.obtenerClientes()
                .stream().filter(c -> c.getDni().equals(txtDniCli.getText()))
                .collect(Collectors.toList());
        if (listaDni.isEmpty()) {
            Cliente cliente = new Cliente();
            cliente.setDni(txtDniCli.getText());
            cliente.setNombre(txtNombreCli.getText());
            cliente.setApellido(txtApellidoCli.getText());
            cliente.setTelefono(txtTelCli.getText());
            cliente.setDireccion(txtDirCli.getText());
            cliente.setCategoriaIva((String) cboCatIva.getSelectedItem());
            int resultado = MetodosSQL.guardarCliente(cliente);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Cliente Guardado con exito!");
                limpiarCampos();
                Home.VENTAS_FRAME.cargarModeloCboCli();
                Home.mostrarPanel(Home.VENTAS_FRAME);
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrio un error intentelo nuevamente");
                txtDniCli.requestFocus();
            }
        } else {
            Helper.mostrarError(txtDniCli, lblDNI, "El DNI ya esta registrado", Color.red);
        }


    }//GEN-LAST:event_btnGuardarClienteMouseClicked

    private void txtNombreCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCliKeyReleased
        if (Helper.esCampoVacio(txtNombreCli)) {
            lblNombreCli.setForeground(Color.white);
        } else {
            lblNombreCli.setText("Nombre:");
            lblNombreCli.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtNombreCliKeyReleased

    private void txtDniCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniCliKeyReleased
        if (Helper.esCampoVacio(txtDniCli)) {
            lblDNI.setForeground(Color.white);
        } else {
            lblDNI.setText("DNI:");
            lblDNI.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtDniCliKeyReleased

    private void txtDniCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniCliActionPerformed

    private void txtTelCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelCliKeyPressed
        Helper.validarSoloNumero(evt, txtTelCli);
    }//GEN-LAST:event_txtTelCliKeyPressed

    private void txtDniCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniCliKeyPressed
        Helper.validarSoloNumero(evt, txtDniCli);
    }//GEN-LAST:event_txtDniCliKeyPressed

    private void txtApellidoCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoCliKeyReleased
        if (Helper.esCampoVacio(txtApellidoCli)) {
            lblApellido.setForeground(Color.white);
        } else {
            lblApellido.setText("Apellidos:");
            lblApellido.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtApellidoCliKeyReleased

    private void txtTelCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelCliKeyReleased
        if (txtTelCli.getText().isEmpty()) {
            lblTelefono.setForeground(Color.white);
        } else {
            lblTelefono.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtTelCliKeyReleased

    private void txtDirCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirCliKeyReleased
        if (txtDirCli.getText().isEmpty()) {
            lblDireccion.setForeground(Color.white);
        } else {
            lblDireccion.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtDirCliKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnGuardarCliente;
    private javax.swing.JPanel btn_regis2;
    private javax.swing.JPanel btn_regis4;
    private javax.swing.JComboBox<String> cboCatIva;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombreCli;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtApellidoCli;
    private javax.swing.JTextField txtDirCli;
    private javax.swing.JTextField txtDniCli;
    private javax.swing.JTextField txtNombreCli;
    private javax.swing.JTextField txtTelCli;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        txtDniCli.setText("");
        txtNombreCli.setText("");
        txtApellidoCli.setText("");
        txtTelCli.setText("");
        txtDirCli.setText("");
        txtDniCli.requestFocus();
    }

}
