/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

/**
 *
 * @author ernes
 */
public class compras extends javax.swing.JPanel {

    /**
     * Creates new form compras
     */
    public compras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id_cli = new javax.swing.JTextField();
        txt_nom_cli = new javax.swing.JTextField();
        txt_tel_cli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dni_cli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tel_cli1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tel_cli2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_tel_cli3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_tel_cli4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_tel_cli5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_tel_cli6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_tel_cli7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tel_cli8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_tel_cli9 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(47, 34, 23));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_id_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_id_cli.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_cli.setText("muestr sifguiente id");
        txt_id_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_cliActionPerformed(evt);
            }
        });
        add(txt_id_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 80, -1));

        txt_nom_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_nom_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_nom_cli.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_nom_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 240, -1));

        txt_tel_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_tel_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 140, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID proveedor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID producto");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID de compra");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compras.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio de compra (ud)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        txt_dni_cli.setBackground(new java.awt.Color(47, 34, 23));
        txt_dni_cli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_dni_cli.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_dni_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 140, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de compra");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        txt_tel_cli1.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli1.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_tel_cli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 140, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        txt_tel_cli2.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli2.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_tel_cli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 140, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio de venta (ud)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txt_tel_cli3.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli3.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_tel_cli3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 140, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Marca");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        txt_tel_cli4.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli4.setForeground(new java.awt.Color(255, 255, 255));
        txt_tel_cli4.setText("tabla prod.");
        add(txt_tel_cli4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 140, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Categoria");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        txt_tel_cli5.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli5.setForeground(new java.awt.Color(255, 255, 255));
        txt_tel_cli5.setText("tabla prod.");
        add(txt_tel_cli5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 140, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stock actual");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        txt_tel_cli6.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli6.setForeground(new java.awt.Color(255, 255, 255));
        txt_tel_cli6.setText("tabla inv.");
        add(txt_tel_cli6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 140, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Limite de stock");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        txt_tel_cli7.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli7.setForeground(new java.awt.Color(255, 255, 255));
        txt_tel_cli7.setText("tabla inv.");
        txt_tel_cli7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tel_cli7ActionPerformed(evt);
            }
        });
        add(txt_tel_cli7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 140, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Descripcion");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        txt_tel_cli8.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_tel_cli8.setForeground(new java.awt.Color(255, 255, 255));
        txt_tel_cli8.setText("tabla prod.");
        add(txt_tel_cli8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 290, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Imagen");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        txt_tel_cli9.setBackground(new java.awt.Color(47, 34, 23));
        txt_tel_cli9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txt_tel_cli9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 140, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_cliActionPerformed

    private void txt_tel_cli7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tel_cli7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tel_cli7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_dni_cli;
    private javax.swing.JTextField txt_id_cli;
    private javax.swing.JTextField txt_nom_cli;
    private javax.swing.JTextField txt_tel_cli;
    private javax.swing.JTextField txt_tel_cli1;
    private javax.swing.JTextField txt_tel_cli2;
    private javax.swing.JTextField txt_tel_cli3;
    private javax.swing.JTextField txt_tel_cli4;
    private javax.swing.JTextField txt_tel_cli5;
    private javax.swing.JTextField txt_tel_cli6;
    private javax.swing.JTextField txt_tel_cli7;
    private javax.swing.JTextField txt_tel_cli8;
    private javax.swing.JTextField txt_tel_cli9;
    // End of variables declaration//GEN-END:variables
}
