/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

import db.MetodosSQL;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import modelos.Producto;

/**
 *
 * @author Horacio
 */
public class Inventario extends javax.swing.JPanel {

   DefaultTableModel modeloTabla = new DefaultTableModel();

     public Inventario() {
          cargarColumnasTabla();
        ArrayList<Producto> productos = MetodosSQL.obtenerProductos();
        cargarModeloTabla(productos);
        initComponents();
        initComponents();
    }
     private void cargarColumnasTabla() {
          modeloTabla.addColumn("#");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Precio Compra");
        modeloTabla.addColumn("Precio Venta");
        modeloTabla.addColumn("Stock");
    }
    private void cargarModeloTabla(ArrayList<Producto> productos) {
      
              int numeroFilas = productos.size();
              modeloTabla.setNumRows(numeroFilas);
        for (int i = 0; i < numeroFilas; i++) {
            Producto p = productos.get(i);
            String codigo = p.getCodigo();
            String nombre = p.getNombre();
            Double precioCompra = p.getPrecioCompra();
            Double precioVenta = p.getPrecioVenta();
            Integer stock = p.getStock();
            modeloTabla.setValueAt(p, i, 0);
            modeloTabla.setValueAt(nombre, i, 1);
            modeloTabla.setValueAt(precioCompra, i, 2);
            modeloTabla.setValueAt(precioVenta, i, 3);
            modeloTabla.setValueAt(stock, i, 4);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JPanel();
        btn_regis3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarProd = new javax.swing.JTextField();
        btnModificarProducto = new javax.swing.JPanel();
        btn_regis2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnNuevoProducto1 = new javax.swing.JPanel();
        btn_regis4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(47, 34, 23));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(modeloTabla);
        jScrollPane1.setViewportView(tablaProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 680, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Buscar:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        btnEliminarProducto.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseClicked(evt);
            }
        });
        btnEliminarProducto.setLayout(new java.awt.GridBagLayout());

        btn_regis3.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis3MouseClicked(evt);
            }
        });
        btn_regis3.setLayout(new java.awt.GridBagLayout());
        btnEliminarProducto.add(btn_regis3, new java.awt.GridBagConstraints());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Eliminar");
        btnEliminarProducto.add(jLabel12, new java.awt.GridBagConstraints());

        add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 110, 40));
        add(txtBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 340, -1));

        btnModificarProducto.setBackground(new java.awt.Color(255, 102, 0));
        btnModificarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarProductoMouseClicked(evt);
            }
        });
        btnModificarProducto.setLayout(new java.awt.GridBagLayout());

        btn_regis2.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis2MouseClicked(evt);
            }
        });
        btn_regis2.setLayout(new java.awt.GridBagLayout());
        btnModificarProducto.add(btn_regis2, new java.awt.GridBagConstraints());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Modificar");
        btnModificarProducto.add(jLabel11, new java.awt.GridBagConstraints());

        add(btnModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 110, 40));

        btnNuevoProducto1.setBackground(new java.awt.Color(255, 102, 0));
        btnNuevoProducto1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoProducto1MouseClicked(evt);
            }
        });
        btnNuevoProducto1.setLayout(new java.awt.GridBagLayout());

        btn_regis4.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis4MouseClicked(evt);
            }
        });
        btn_regis4.setLayout(new java.awt.GridBagLayout());
        btnNuevoProducto1.add(btn_regis4, new java.awt.GridBagConstraints());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nuevo");
        btnNuevoProducto1.add(jLabel13, new java.awt.GridBagConstraints());

        add(btnNuevoProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regis3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis3MouseClicked

    private void btnEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProductoMouseClicked

    private void btn_regis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis2MouseClicked

    private void btnModificarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarProductoMouseClicked
        /*
        int i = metodos.guardar_inv(txt_nom_inv.getText(), txt_pre_com_inv.getText(),txt_pre_ven_inv.getText(), txt_id_prove.getText(), txt_cant_inv.getText(),txt_url_inv.getText(),txt_descr_inv.getText());

        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Datos guardados corectamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar los datos");
        }
        */
    }//GEN-LAST:event_btnModificarProductoMouseClicked

    private void btn_regis4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis4MouseClicked

    private void btnNuevoProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoProducto1MouseClicked
        //        true para abrir como ventana modal
        ProductoFrame productoFrame = new ProductoFrame(null, true, null, null, "Nuevo Producto", false);
        productoFrame.setVisible(true);
        productoFrame.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
        productoFrame.setLocation(600, 150);
        productoFrame.setAlwaysOnTop(true);
    }//GEN-LAST:event_btnNuevoProducto1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEliminarProducto;
    private javax.swing.JPanel btnModificarProducto;
    private javax.swing.JPanel btnNuevoProducto1;
    private javax.swing.JPanel btn_regis2;
    private javax.swing.JPanel btn_regis3;
    private javax.swing.JPanel btn_regis4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBuscarProd;
    // End of variables declaration//GEN-END:variables
}
