/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesPanels;

import static FramesPanels.Home.contenedor;
import db.MetodosSQL;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelos.Producto;

/**
 *
 * @author Horacio
 */
public class Inventario extends javax.swing.JPanel {

    static DefaultTableModel modeloTabla = new DefaultTableModel();
    private Producto productoSeleccionado = null;

    public Inventario() {
        cargarColumnasTabla();
        cargarModeloTabla(null);
        initComponents();

    }

    private static void limpiarTabla() {
        int numFilas = modeloTabla.getRowCount();
        if (numFilas > 0) {
            for (int i = numFilas - 1; i >= 0; i--) {
                modeloTabla.removeRow(i);
            }
        }
    }

    private void cargarImagen(Producto p) {
        ImageIcon imagenProd = null;
        try {
            InputStream is = MetodosSQL.buscarFoto(p);
            BufferedImage bi = null;
            if (is != null) {
            
                 bi = ImageIO.read(is);
                    imagenProd = new ImageIcon(bi);
            } else {
                imagenProd = new ImageIcon(getClass().getResource("/images/no_img.jpg"));
            }
           
            //Redimensión de imagen para ajustarla al tamaño del JLabel.
            Image imgProd = imagenProd.getImage();
            int anchoEtiqueta = lblImagenProd.getWidth(); //Obtiene ancho de la imagen
            int altoEtiqueta = lblImagenProd.getHeight(); //Obtiene alto de la imagen

            //Se crea un nuevo objeto Image con la imagen redimensionada.
            Image imgRedimensionada = imgProd.getScaledInstance(250, 150, Image.SCALE_DEFAULT);
            //Se crea un nuevo objeto ImageIcon a partir de la imagen redimensionada.
            ImageIcon iconRedimensionado = new ImageIcon(imgRedimensionada);

            //Establecemos la imagen redimensionada, como icono de la etiqueta de imagen.
            lblImagenProd.setIcon(iconRedimensionado);
        } catch (IOException e ) {
        }
    }

    private void cargarColumnasTabla() {
        modeloTabla.addColumn("#");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Precio Compra");
        modeloTabla.addColumn("Precio Venta");
        modeloTabla.addColumn("Stock");
    }

    public static void cargarModeloTabla(String filtro) {
        limpiarTabla();
        ArrayList<Producto> productos;
        if (filtro == null) {
            productos = MetodosSQL.obtenerProductos();
        } else {
            productos = MetodosSQL.obtenerProductosPorCriterio(filtro);

        }
        int numeroFilas = productos.size();

        modeloTabla.setNumRows(numeroFilas);
        // recorrer productos y insertar en la tabla
        for (int i = 0; i < numeroFilas; i++) {
            Producto p = productos.get(i);
            String codigo = p.getCodigo();
            String nombre = p.getNombre();
            Double precioCompra = p.getPrecioCompra();
            Double precioVenta = p.getPrecioVenta();
            Integer stock = p.getStock();
            modeloTabla.setValueAt(codigo, i, 0);
            modeloTabla.setValueAt(p, i, 1);
            modeloTabla.setValueAt(precioCompra, i, 2);
            modeloTabla.setValueAt(precioVenta, i, 3);
            modeloTabla.setValueAt(stock, i, 4);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JPanel();
        btn_regis3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarProd = new javax.swing.JTextField();
        btnModificarProducto = new javax.swing.JPanel();
        btn_regis2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnNuevoProducto1 = new javax.swing.JPanel();
        btn_regis4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImagenProd = new javax.swing.JLabel();

        setBackground(new java.awt.Color(47, 34, 23));
        setPreferredSize(new java.awt.Dimension(1270, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(modeloTabla);
        tablaProductos.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    if (!event.getValueIsAdjusting() && (tablaProductos.getSelectedRow()>= 0)) {//This line prevents double events
                        int filaSeleccionada = tablaProductos.getSelectedRow();
                        Producto producto = (Producto)modeloTabla.getValueAt(filaSeleccionada, 1);
                        txtNombreProducto.setText(producto.getNombre().toUpperCase());
                        txtCodigoProducto.setText(producto.getCodigo().toUpperCase());
                        productoSeleccionado = producto;
                        cargarImagen(producto);
                    }
                }
            }
        );
        jScrollPane1.setViewportView(tablaProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 680, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombre:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        btnEliminarProducto.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseClicked(evt);
            }
        });
        btnEliminarProducto.setLayout(new java.awt.GridBagLayout());

        btn_regis3.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis3MouseClicked(evt);
            }
        });
        btn_regis3.setLayout(new java.awt.GridBagLayout());
        btnEliminarProducto.add(btn_regis3, new java.awt.GridBagConstraints());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Eliminar");
        btnEliminarProducto.add(jLabel12, new java.awt.GridBagConstraints());

        add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, 110, 40));

        txtBuscarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProdKeyReleased(evt);
            }
        });
        add(txtBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 340, -1));

        btnModificarProducto.setBackground(new java.awt.Color(255, 102, 0));
        btnModificarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarProductoMouseClicked(evt);
            }
        });
        btnModificarProducto.setLayout(new java.awt.GridBagLayout());

        btn_regis2.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis2MouseClicked(evt);
            }
        });
        btn_regis2.setLayout(new java.awt.GridBagLayout());
        btnModificarProducto.add(btn_regis2, new java.awt.GridBagConstraints());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Modificar");
        btnModificarProducto.add(jLabel11, new java.awt.GridBagConstraints());

        add(btnModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 110, 40));

        btnNuevoProducto1.setBackground(new java.awt.Color(255, 102, 0));
        btnNuevoProducto1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoProducto1MouseClicked(evt);
            }
        });
        btnNuevoProducto1.setLayout(new java.awt.GridBagLayout());

        btn_regis4.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_regis4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis4MouseClicked(evt);
            }
        });
        btn_regis4.setLayout(new java.awt.GridBagLayout());
        btnNuevoProducto1.add(btn_regis4, new java.awt.GridBagConstraints());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nuevo");
        btnNuevoProducto1.add(jLabel13, new java.awt.GridBagConstraints());

        add(btnNuevoProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 110, 40));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(245, 345));
        jPanel2.setPreferredSize(new java.awt.Dimension(233, 575));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 740));

        txtNombreProducto.setEnabled(false);
        add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 380, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Codigo:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        txtCodigoProducto.setEnabled(false);
        add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 270, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Buscar:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 250, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regis3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis3MouseClicked

    private void btnEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseClicked
        if (productoSeleccionado != null) {

            int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de borrar el producto "
                    + productoSeleccionado + " ?");

            if (opcion == 0) {
                modeloTabla.removeRow(tablaProductos.getSelectedRow());
                MetodosSQL.borrarProducto(productoSeleccionado);
                txtCodigoProducto.setText("");
                txtNombreProducto.setText("");
                txtBuscarProd.setText("");
                txtBuscarProd.requestFocus();
                productoSeleccionado = null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto de la tabla");
        }
    }//GEN-LAST:event_btnEliminarProductoMouseClicked

    private void btn_regis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis2MouseClicked

    private void btnModificarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarProductoMouseClicked
        if (productoSeleccionado != null) {
            ImageIcon imagenProducto = null;
            ProductoFrame productoFrame = null;
            try {
                /*obtener imagen*/
                InputStream is = MetodosSQL.buscarFoto(productoSeleccionado);
                if (is != null) {
                    BufferedImage bi = ImageIO.read(is);
                    imagenProducto = new ImageIcon(bi);

                    /*crear ventana de actualización*/
                    Home.PRODUCTO_FRAME.cargarProducto(productoSeleccionado, imagenProducto);
                } else {
                    Home.PRODUCTO_FRAME.cargarProducto(productoSeleccionado, null);
                }
                Home.mostrarPanel(Home.PRODUCTO_FRAME);
            } catch (IOException ex) {
                ex.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto de la tabla");
        }
    }//GEN-LAST:event_btnModificarProductoMouseClicked

    private void btn_regis4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis4MouseClicked

    private void btnNuevoProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoProducto1MouseClicked
        //        true para abrir como ventana modal
        Home.INVENTARIO.setVisible(false);
        Home.PRODUCTO_FRAME.setVisible(true);
        Home.PRODUCTO_FRAME.reiniciarPanel();
        Home.contenedor.remove(this);
        Home.contenedor.add(Home.PRODUCTO_FRAME);
        Home.contenedor.revalidate();
        Home.contenedor.repaint();
    }//GEN-LAST:event_btnNuevoProducto1MouseClicked

    private void txtBuscarProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProdKeyReleased
        String cadenaBusqueda = txtBuscarProd.getText().toLowerCase();
        cargarModeloTabla(cadenaBusqueda);

    }//GEN-LAST:event_txtBuscarProdKeyReleased
    public void reiniciarPanel() {
        txtCodigoProducto.setText("");
        txtNombreProducto.setText("");
        txtBuscarProd.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEliminarProducto;
    private javax.swing.JPanel btnModificarProducto;
    private javax.swing.JPanel btnNuevoProducto1;
    private javax.swing.JPanel btn_regis2;
    private javax.swing.JPanel btn_regis3;
    private javax.swing.JPanel btn_regis4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagenProd;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBuscarProd;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
