
package FramesPanels;

import javax.swing.JOptionPane;
import metodos_sql.metodos_sql;

public class Inventario extends javax.swing.JPanel {

    public Inventario() {
        initComponents();
    }
    
    metodos_sql metodos = new metodos_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id_inv = new javax.swing.JTextField();
        txt_nom_inv = new javax.swing.JTextField();
        txt_pre_com_inv = new javax.swing.JTextField();
        txt_pre_ven_inv = new javax.swing.JTextField();
        txt_cant_inv = new javax.swing.JTextField();
        txt_descr_inv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_id_prove = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_url_inv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_regis = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_regis1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(47, 34, 23));
        setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 575));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_inv.setBackground(new java.awt.Color(47, 34, 23));
        txt_id_inv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_id_inv.setForeground(new java.awt.Color(255, 255, 255));
        txt_id_inv.setText("muestr sifguiente id");
        txt_id_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_invActionPerformed(evt);
            }
        });
        add(txt_id_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 70, -1));

        txt_nom_inv.setBackground(new java.awt.Color(47, 34, 23));
        txt_nom_inv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_nom_inv.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_nom_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 260, -1));

        txt_pre_com_inv.setBackground(new java.awt.Color(47, 34, 23));
        txt_pre_com_inv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_pre_com_inv.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_pre_com_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 100, -1));

        txt_pre_ven_inv.setBackground(new java.awt.Color(47, 34, 23));
        txt_pre_ven_inv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_pre_ven_inv.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_pre_ven_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 100, -1));

        txt_cant_inv.setBackground(new java.awt.Color(47, 34, 23));
        txt_cant_inv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_cant_inv.setForeground(new java.awt.Color(255, 255, 255));
        txt_cant_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant_invActionPerformed(evt);
            }
        });
        add(txt_cant_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 80, -1));

        txt_descr_inv.setBackground(new java.awt.Color(47, 34, 23));
        txt_descr_inv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_descr_inv.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_descr_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 260, 90));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("id");
        jLabel1.setInheritsPopupMenu(false);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jLabel2.setInheritsPopupMenu(false);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio de compra");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio de venta");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("cantidad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripción");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        txt_id_prove.setBackground(new java.awt.Color(47, 34, 23));
        txt_id_prove.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_id_prove.setForeground(new java.awt.Color(255, 255, 255));
        add(txt_id_prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 80, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id proveedor");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        txt_url_inv.setBackground(new java.awt.Color(47, 34, 23));
        txt_url_inv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_url_inv.setForeground(new java.awt.Color(255, 255, 255));
        txt_url_inv.setText("url");
        add(txt_url_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 160, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Imagen");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(245, 345));
        jPanel1.setPreferredSize(new java.awt.Dimension(233, 575));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        btn_regis.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regisMouseClicked(evt);
            }
        });
        btn_regis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar");
        btn_regis.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        add(btn_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 90, 30));

        btn_regis1.setBackground(new java.awt.Color(255, 102, 0));
        btn_regis1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regis1MouseClicked(evt);
            }
        });
        btn_regis1.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Guardar");
        btn_regis1.add(jLabel11, new java.awt.GridBagConstraints());

        add(btn_regis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_invActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_invActionPerformed

    private void txt_cant_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant_invActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant_invActionPerformed

    private void btn_regisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regisMouseClicked

    }//GEN-LAST:event_btn_regisMouseClicked

    private void btn_regis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regis1MouseClicked

        int i = metodos.guardar_inv(txt_nom_inv.getText(), txt_pre_com_inv.getText(),txt_pre_ven_inv.getText(), txt_id_prove.getText(), txt_cant_inv.getText(),txt_url_inv.getText(),txt_descr_inv.getText());

        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Datos guardados corectamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar los datos");
        }
    }//GEN-LAST:event_btn_regis1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_regis;
    private javax.swing.JPanel btn_regis1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_cant_inv;
    private javax.swing.JTextField txt_descr_inv;
    private javax.swing.JTextField txt_id_inv;
    private javax.swing.JTextField txt_id_prove;
    private javax.swing.JTextField txt_nom_inv;
    private javax.swing.JTextField txt_pre_com_inv;
    private javax.swing.JTextField txt_pre_ven_inv;
    private javax.swing.JTextField txt_url_inv;
    // End of variables declaration//GEN-END:variables
}
